-- DDL for creating the PERSONS table in Db2 for z/OS
-- Final version: Renamed create_ts, made middle_name nullable, removed age.

CREATE TABLE PERSONS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    FULL_NAME VARCHAR(150) NOT NULL,
    FIRST_NAME VARCHAR(50),
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(25) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    SSN_ITIN CHAR(9) NOT NULL,
    ENTITY_TYPE CHAR(1) NOT NULL WITH DEFAULT 'I',
    STREET_ADDRESS VARCHAR(200) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE CHAR(2) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL WITH DEFAULT 'United States',
    CREATE_TS TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_PERSONS PRIMARY KEY (ID),
    CONSTRAINT CHK_ENTITY_TYPE CHECK (ENTITY_TYPE IN ('I', 'B'))
)
IN DATABASE YOURDB; -- Specify your Database name
-- IN TABLESPACE YOURTS; -- Optionally specify your Tablespace

-- Indexes
CREATE INDEX IDX_FULL_NAME ON PERSONS (FULL_NAME);
CREATE INDEX IDX_FIRST_NAME ON PERSONS (FIRST_NAME);
CREATE INDEX IDX_LAST_NAME ON PERSONS (LAST_NAME);
CREATE UNIQUE INDEX IDX_EMAIL ON PERSONS (EMAIL);
CREATE INDEX IDX_STATE ON PERSONS (STATE);
CREATE INDEX IDX_ZIP_CODE ON PERSONS (ZIP_CODE);
CREATE INDEX IDX_BIRTHDATE ON PERSONS (BIRTHDATE);
CREATE UNIQUE INDEX IDX_SSN_ITIN ON PERSONS (SSN_ITIN);
CREATE INDEX IDX_ENTITY_TYPE ON PERSONS (ENTITY_TYPE);

-- Comments
COMMENT ON TABLE PERSONS IS 'US persons/businesses with addresses, birthdates, SSN/ITIN. Full address is composed from address parts.';

COMMENT ON COLUMN PERSONS.ID IS 'Auto-generated unique identifier';
COMMENT ON COLUMN PERSONS.FULL_NAME IS 'Full name (first + middle + last) or business name';
COMMENT ON COLUMN PERSONS.FIRST_NAME IS 'First name only (null for business)';
COMMENT ON COLUMN PERSONS.MIDDLE_NAME IS 'Middle name (optional, null if none)';
COMMENT ON COLUMN PERSONS.LAST_NAME IS 'Last name only (null for business)';
COMMENT ON COLUMN PERSONS.EMAIL IS 'Email address';
COMMENT ON COLUMN PERSONS.PHONE IS 'US phone number with extensions';
COMMENT ON COLUMN PERSONS.BIRTHDATE IS 'Date of birth (YYYY-MM-DD) or business founding date';
COMMENT ON COLUMN PERSONS.SSN_ITIN IS 'SSN or ITIN (XXXXXXXXX format, no dashes). Sensitive data, ensure encryption.';
COMMENT ON COLUMN PERSONS.ENTITY_TYPE IS 'Entity type: I=individual, B=business';
COMMENT ON COLUMN PERSONS.STREET_ADDRESS IS 'US street address';
COMMENT ON COLUMN PERSONS.CITY IS 'US city name';
COMMENT ON COLUMN PERSONS.STATE IS 'US state abbreviation (CA, NY, TX, etc)';
COMMENT ON COLUMN PERSONS.ZIP_CODE IS 'US ZIP code (12345 or 12345-6789)';
COMMENT ON COLUMN PERSONS.COUNTRY IS 'Country name';
COMMENT ON COLUMN PERSONS.CREATE_TS IS 'Record creation timestamp';