CREATE TABLE DTRBDDBA.DEMO_ENTITIES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TIN CHAR(9) NOT NULL,
    ENTITY_TYPE CHAR(1) NOT NULL WITH DEFAULT 'I',
    LEGAL_NAME VARCHAR(150) NOT NULL,
    FIRST_NAME VARCHAR(50),
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100) NOT NULL,
    PHONE CHAR(10) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    STREET_ADDRESS VARCHAR(200) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE CHAR(2) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL WITH DEFAULT 'United States',
    CREATE_TS TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_DEMO_ENTITIES PRIMARY KEY (ID),
    CONSTRAINT CHK_DEMO_ENTITY_TYPE CHECK (ENTITY_TYPE IN ('I', 'B'))
)
IN DATABASE YOURDB -- Specify the target Database name
IN DTRBDDBA.STRDEN;

CREATE UNIQUE INDEX DTRBDDBA.SDX_DEMO_ENTITIES_TIN
    ON DTRBDDBA.DEMO_ENTITIES (TIN);