let
    // 1. SharePoint site root URL
    SiteUrl = "https://yourcompany.sharepoint.com/sites/yoursite",

    // 2. Excel file name
    FileName = "sales.xlsx",

    // 3. Read file list from SharePoint
    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),

    // 4. Keep only the target file
    FilteredFile = Table.SelectRows(Source, each [Name] = FileName),

    // 5. Get file content as binary
    FileBinary = FilteredFile{0}[Content],

    // 6. Read the Excel workbook, sheet name is "year"
    Workbook = Excel.Workbook(FileBinary, null, true),
    RawSheet = Workbook{[Item="year", Kind="Sheet"]}[Data],

    // 7. Read the first two header rows
    FirstRow = RawSheet{0},
    SecondRow = RawSheet{1},
    OriginalColumnNames = Table.ColumnNames(RawSheet),

    // 8. Read the first header row values
    FirstRowValues =
        List.Transform(
            OriginalColumnNames,
            each try Record.Field(FirstRow, _) otherwise null
        ),

    // 9. Fill empty year cells from left to right
    FilledYearValues =
        List.Accumulate(
            FirstRowValues,
            {},
            (state, current) =>
                let
                    CurrentText = if current = null then "" else Text.Trim(Text.From(current)),
                    FilledValue =
                        if CurrentText <> "" then
                            CurrentText
                        else if List.Count(state) = 0 then
                            ""
                        else
                            List.Last(state)
                in
                    state & {FilledValue}
        ),

    // 10. Combine the two header rows into unique column names
    NewColumnNames =
        List.Transform(
            List.Positions(OriginalColumnNames),
            (i) =>
                let
                    YearText = FilledYearValues{i},
                    MetricValue = try Record.Field(SecondRow, OriginalColumnNames{i}) otherwise null,
                    MetricText = if MetricValue = null then "" else Text.Trim(Text.From(MetricValue))
                in
                    if i = 0 then
                        "Month"
                    else
                        MetricText & "_" & YearText
        ),

    // 11. Skip the first two header rows and keep only data rows
    DataRows = Table.Skip(RawSheet, 2),

    // 12. Rebuild the table with the new column names
    RenamedTable = Table.FromColumns(Table.ToColumns(DataRows), NewColumnNames),

    // 13. Remove fully blank rows
    RemovedBlankRows = Table.SelectRows(RenamedTable, each List.NonNullCount(Record.FieldValues(_)) > 0),

    // 14. Unpivot all metric columns into attribute-value pairs
    Unpivoted = Table.UnpivotOtherColumns(RemovedBlankRows, {"Month"}, "Attribute", "Value"),

    // 15. Split the combined attribute into Metric and Year
    SplitAttribute = Table.SplitColumn(
        Unpivoted,
        "Attribute",
        Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv),
        {"Metric", "Year"}
    ),

    // 16. Set data types for the final columns
    ChangedType = Table.TransformColumnTypes(
        SplitAttribute,
        {
            {"Month", type text},
            {"Metric", type text},
            {"Year", Int64.Type},
            {"Value", type number}
        }
    ),

    // 17. Reorder columns for the final output
    ReorderedColumns = Table.ReorderColumns(ChangedType, {"Month", "Year", "Metric", "Value"})
in
    ReorderedColumns